a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('controllers/*.py', 'controllers'),
        ('auth/*.py', 'auth'),
        ('Scraper.py', '.'),
        ('services/*.py', 'services'),
        ('helper/*.py', 'helper'),
        ('database/*.py', 'database'),
        ('config/*.py', 'config'),
        ('tradingbinance/*.py', 'tradingbinance'),
    ],
    hiddenimports=[
        'eventlet.hubs.epolls', 'eventlet.hubs.kqueue', 'eventlet.hubs.selects',
        'dns', 'dns.dnssec', 'dns.e164', 'dns.hash', 'dns.versioned', 'dns.namedict',
        'dns.tsigkeyring', 'dns.update', 'dns.version', 'dns.zone', 'jwt', 'pymongo',
        'selenium', 'aiohappyeyeballs', 'aiohttp', 'aiosignal', 'altgraph', 'attrs',
        'beautifulsoup4', 'bidict', 'binance', 'blinker', 'certifi', 'cffi',
        'charset_normalizer', 'click', 'cryptography', 'dateparser', 'dnspython',
        'eventlet', 'Flask', 'Flask-Cors', 'Flask-SocketIO', 'frozenlist', 'gevent',
        'gevent-websocket', 'greenlet', 'h11', 'idna', 'itsdangerous', 'Jinja2',
        'macholib', 'MarkupSafe', 'marshmallow', 'multidict', 'outcome', 'packaging',
        'playwright', 'propcache', 'pycparser', 'pycryptodome', 'pyee', 'pyinstaller',
        'pyinstaller-hooks-contrib', 'PyJWT', 'PySocks', 'python-binance',
        'selenium.webdriver.support.ui', 'webdriver_manager',
        'python-dateutil', 'python-dotenv', 'python-engineio', 'python-socketio',
        'pytz', 'regex', 'requests', 'selenium-stealth', 'selenium', 'selenium.common', 'setuptools',
        'simple-websocket', 'six', 'sniffio', 'sortedcontainers', 'soupsieve', 'trio',
        'selenium.webdriver.chrome', 'selenium.webdriver.support',
        'selenium.webdriver.support.expected_conditions',
        'trio-websocket', 'TwoCaptcha', 'typing_extensions', 'tzlocal', 'urllib3',
        'webdriver-manager', 'websocket-client', 'websockets', 'Werkzeug', 'wsproto',
        'yarl', 'zope.event', 'zope.interface', 'gevent'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
